//! Endpoint 4: the seeded stratified sample of (commit, topic) pairs flagged by
//! T_file but not T_sym, one judge prompt per pair, and the scoring of the
//! verdicts once independent judges have written them. Nothing here produces a
//! verdict.

use std::path::Path;

use serde::{Deserialize, Serialize};
use serde_json::{Value, json};

use crate::git::Repo;
use crate::report::HIDDEN_CEILING;
use crate::stats;
use crate::topics::{RepoKey, Topic};
use crate::{RepoRun, topics};

/// Pairs drawn per stratum.
pub const STRATA: [(RepoKey, usize); 2] = [(RepoKey::Visionclaw, 30), (RepoKey::Agentbox, 10)];

/// The pre-registered question, verbatim.
pub const QUESTION: &str = "Does this change make any statement in the topic false or incomplete?";

/// One drawn pair.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Pair {
    pub id: String,
    pub repo: String,
    pub commit: String,
    pub parent: String,
    pub topic: String,
    pub commit_precedes_stamp: bool,
    pub diff_lines: usize,
    pub prompt: String,
}

/// The drawn sample and the populations it came from.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Sample {
    pub population: Vec<(String, usize)>,
    pub pairs: Vec<Pair>,
}

impl Sample {
    /// The `endpoint4` block of `results.json`.
    pub fn to_json(&self) -> Value {
        let pop: serde_json::Map<String, Value> = self.population.iter().map(|(k, n)| (k.clone(), json!(n))).collect();
        let count = |k: &str| self.pairs.iter().filter(|p| p.repo == k).count();
        json!({
            "status": "PENDING",
            "reason": "no Agent tool in the harness context; prompts prepared, no verdict produced",
            "question": QUESTION,
            "seed": stats::SEED,
            "population": pop,
            "drawn": {"visionclaw": count("visionclaw"), "agentbox": count("agentbox"), "total": self.pairs.len()},
            "sample": self.pairs,
        })
    }
}

fn fence(body: &str) -> String {
    let mut longest = 0;
    let mut run = 0;
    for ch in body.chars() {
        if ch == '`' {
            run += 1;
            longest = longest.max(run);
        } else {
            run = 0;
        }
    }
    "`".repeat((longest + 1).max(3))
}

fn prompt(id: &str, repo: &str, topic: &Topic, diff: &str) -> String {
    let tf = fence(&topic.text);
    let df = fence(diff);
    format!(
        "# E0 judgement {id}\n\n\
You are an independent judge for a pre-registered experiment. Below are (1) a TOPIC: a Markdown file of Mermaid \
diagrams that document code, with `path:line` citations, where paths under `../project/` are in the VisionClaw \
repository and paths under `../project/agentbox/` are in the agentbox repository; and (2) a DIFF: one commit's \
changes in the {repo} repository, restricted to the files the topic lists under `sources:`.\n\n\
Answer exactly one question:\n\n> **{QUESTION}**\n\n\
Judge only from the two texts below; do not look anything else up. Reply with a single JSON object and nothing else:\n\n\
```json\n{{\"verdict\": \"yes\" | \"no\", \"statements\": [\"<diagram id>: <the statement, quoted>\", ...], \
\"line_anchors_only\": true | false, \"reason\": \"<one or two sentences>\"}}\n```\n\n\
`statements` lists every topic statement the change makes false or incomplete (empty when the verdict is no). \
`line_anchors_only` is true when the only such statements are `path:line` anchors whose cited code merely moved.\n\n\
## TOPIC ({file})\n\n{tf}markdown\n{text}\n{tf}\n\n## DIFF\n\n{df}diff\n{diff}\n{df}\n",
        file = topic.file,
        text = topic.text.trim_end(),
        diff = diff.trim_end(),
    )
}

const PROTOCOL: &str = "# Endpoint 4 judging protocol\n\n\
Generated by `e0 run`. Do not edit.\n\n\
1. Each `<id>.prompt.md` is given, unchanged, to a fresh Claude subagent with no other context. Its reply (one JSON \
object) is saved as `<id>.j1.json`.\n\
2. Every pair whose first verdict is `yes` is given, unchanged, to a second fresh subagent, independent of the first \
(it does not see the first verdict). Its reply is saved as `<id>.j2.json`.\n\
3. A pair is a **hidden real change** when both judges answer `yes`. A first `yes` the second judge does not confirm \
counts as not hidden.\n\
4. `e0 score --out docs/evidence/E0` computes the hidden-real-change rate per stratum and pooled, with the Wilson 95% \
upper bound, and writes `endpoint4.json` and `ENDPOINT4.md`. **Success:** pooled rate ≤ 10%.\n\n\
The judge must not be the context that drew the sample or wrote the harness. `line_anchors_only` is recorded so a \
reader can see how many `yes` verdicts rest only on moved line anchors; it does not change the pre-registered \
scoring.\n";

/// Draw the sample and write `judge/` (prompts, `sample.json`, `PROTOCOL.md`).
/// Existing prompt files are replaced; verdict files are never touched.
pub fn prepare(out: &Path, all: &[Topic], runs: &[RepoRun], repos: &[(RepoKey, Repo)]) -> Result<Sample, String> {
    let dir = out.join("judge");
    std::fs::create_dir_all(&dir).map_err(|e| format!("{}: {e}", dir.display()))?;
    for e in std::fs::read_dir(&dir).map_err(|e| e.to_string())?.flatten() {
        if e.file_name().to_string_lossy().ends_with(".prompt.md") {
            let _ = std::fs::remove_file(e.path());
        }
    }
    let mut rng = stats::rng();
    let mut population = Vec::new();
    let mut pairs = Vec::new();
    for (key, k) in STRATA {
        let run = runs.iter().find(|r| r.key == key).ok_or("missing run")?;
        let repo = &repos.iter().find(|(r, _)| *r == key).ok_or("missing repo")?.1;
        let mut pool = Vec::new();
        for row in &run.rows {
            for (ti, f) in &row.flags {
                if f.file && !f.sym {
                    pool.push((row.sha.clone(), row.parent.clone(), *ti));
                }
            }
        }
        population.push((key.as_str().to_string(), pool.len()));
        let prefix = match key {
            RepoKey::Visionclaw => "vc",
            RepoKey::Agentbox => "ab",
        };
        for (i, (sha, parent, ti)) in stats::draw(&pool, k, &mut rng).into_iter().enumerate() {
            let id = format!("{prefix}-{:02}", i + 1);
            let topic = &all[ti];
            let mut srcs: Vec<String> = topic
                .sources
                .iter()
                .filter_map(|s| match topics::repo_of(s) {
                    (Some(r), rel) if r == key.as_str() => Some(rel),
                    _ => None,
                })
                .collect();
            srcs.sort();
            srcs.dedup();
            let diff = repo.diff(&parent, &sha, &srcs)?;
            let file = format!("{id}.prompt.md");
            std::fs::write(dir.join(&file), prompt(&id, key.as_str(), topic, &diff)).map_err(|e| e.to_string())?;
            pairs.push(Pair {
                id,
                repo: key.as_str().into(),
                commit: sha.clone(),
                parent,
                topic: topic.id.clone(),
                commit_precedes_stamp: run.precedes_stamp.get(&(sha, ti)).copied().unwrap_or(false),
                diff_lines: diff.lines().count(),
                prompt: format!("judge/{file}"),
            });
        }
    }
    let sample = Sample { population, pairs };
    let text = serde_json::to_string_pretty(&sample).map_err(|e| e.to_string())? + "\n";
    std::fs::write(dir.join("sample.json"), text).map_err(|e| e.to_string())?;
    std::fs::write(dir.join("PROTOCOL.md"), PROTOCOL).map_err(|e| e.to_string())?;
    Ok(sample)
}

#[derive(Deserialize)]
struct Verdict {
    verdict: String,
}

fn verdict(path: &Path) -> Result<Option<bool>, String> {
    let Ok(text) = std::fs::read_to_string(path) else { return Ok(None) };
    let v: Verdict = serde_json::from_str(text.trim()).map_err(|e| format!("{}: {e}", path.display()))?;
    match v.verdict.to_ascii_lowercase().as_str() {
        "yes" => Ok(Some(true)),
        "no" => Ok(Some(false)),
        other => Err(format!("{}: verdict `{other}` is neither yes nor no", path.display())),
    }
}

/// Score the judges' verdicts against the pre-registered rule.
pub fn score(out: &Path) -> Result<(), String> {
    let dir = out.join("judge");
    let sample: Sample = serde_json::from_str(
        &std::fs::read_to_string(dir.join("sample.json")).map_err(|e| format!("judge/sample.json: {e}"))?,
    )
    .map_err(|e| format!("judge/sample.json: {e}"))?;
    let mut missing = Vec::new();
    let mut rows = Vec::new();
    for p in &sample.pairs {
        let j1 = verdict(&dir.join(format!("{}.j1.json", p.id)))?;
        let j2 = verdict(&dir.join(format!("{}.j2.json", p.id)))?;
        match (j1, j2) {
            (None, _) => missing.push(format!("{}.j1.json", p.id)),
            (Some(true), None) => missing.push(format!("{}.j2.json", p.id)),
            (Some(a), b) => rows.push((p, a, b, a && b == Some(true))),
        }
    }
    if !missing.is_empty() {
        return Err(format!("missing verdicts: {}", missing.join(", ")));
    }
    let block = |repo: Option<&str>| {
        let sel: Vec<_> = rows.iter().filter(|r| repo.is_none_or(|k| r.0.repo == k)).collect();
        let n = sel.len();
        let k = sel.iter().filter(|r| r.3).count();
        let first_yes = sel.iter().filter(|r| r.1).count();
        json!({"n": n, "first_judge_yes": first_yes, "hidden_real": k,
               "rate": if n == 0 { Value::Null } else { json!(k as f64 / n as f64) },
               "wilson95_upper": stats::wilson_upper(k, n)})
    };
    let pooled = block(None);
    let rate = pooled["rate"].as_f64().unwrap_or(f64::NAN);
    let pass = rate <= HIDDEN_CEILING;
    let doc = json!({
        "question": QUESTION,
        "visionclaw": block(Some("visionclaw")),
        "agentbox": block(Some("agentbox")),
        "pooled": pooled,
        "threshold": HIDDEN_CEILING,
        "result": if pass { "PASS" } else { "FAIL" },
        "pairs": rows.iter().map(|(p, a, b, h)| json!({"id": p.id, "j1": a, "j2": b, "hidden_real": h})).collect::<Vec<_>>(),
    });
    std::fs::write(out.join("endpoint4.json"), serde_json::to_string_pretty(&doc).map_err(|e| e.to_string())? + "\n")
        .map_err(|e| e.to_string())?;
    let md = format!(
        "# E0 endpoint 4: hidden-change precision\n\nGenerated by `e0 score` from the verdicts in `judge/`.\n\n| | n | first-judge yes | hidden real (both yes) | rate | Wilson 95% upper |\n|---|---|---|---|---|---|\n{}\n**Result:** pooled rate {} against a ceiling of 10%: **{}**.\n",
        ["visionclaw", "agentbox", "pooled"]
            .iter()
            .map(|k| {
                let b = &doc[*k];
                format!(
                    "| {k} | {} | {} | {} | {:.3} | {:.3} |",
                    b["n"],
                    b["first_judge_yes"],
                    b["hidden_real"],
                    b["rate"].as_f64().unwrap_or(f64::NAN),
                    b["wilson95_upper"].as_f64().unwrap_or(f64::NAN)
                )
            })
            .collect::<Vec<_>>()
            .join("\n"),
        format_args!("{rate:.3}"),
        doc["result"].as_str().unwrap_or(""),
    );
    std::fs::write(out.join("ENDPOINT4.md"), md).map_err(|e| e.to_string())?;
    eprintln!("endpoint 4: {} (pooled rate {rate:.3})", doc["result"].as_str().unwrap_or(""));
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn fences_outgrow_their_content() {
        assert_eq!(fence("plain"), "```");
        assert_eq!(fence("a ```mermaid b"), "````");
        assert_eq!(fence("`````"), "``````");
    }
}
